export declare type IConNameType =
  | 'AccountBookOutlined'
  | 'UpOutlined'
  | 'LeftOutlined'
  | 'RightOutlined'
  | 'CaretUpOutlined'
  | 'CaretDownOutlined'
  | 'CaretLeftOutlined'
  | 'CaretRightOutlined'
  | 'UpCircleOutlined'
  | 'DownCircleOutlined'
  | 'LeftCircleOutlined'
  | 'RightCircleOutlined'
  | 'VerticalAlignBottomOutlined'
  | 'RetweetOutlined'
  | 'QuestionCircleOutlined'
  | 'PlusOutlined'
  | 'CloseOutlined'
  | 'CloseCircleOutlined'
  | 'CloseSquareOutlined'
  | 'CheckOutlined'
  | 'ClockCircleOutlined'
  | 'WarningOutlined'
  | 'BgColorsOutlined'
  | 'AppstoreOutlined'
  | 'ConsoleSqlOutlined'

  // Custom Icon
  | 'WemixLogo'
  | 'NavShop';
